language: python
python:
- '2.7'
- '3.6'
install:
- python setup.py install
script: nosetests
before_install:
  pip install codecov
after_success:
  codecov
deploy:
  provider: pypi
  on:
    tags: true
  user: gollth
  password:
    secure: "Q8A1G7juz8lav5j/81Uanmh/fSiIr46q2bcVc8JwTIDGk4OAnrY0N0EdpUXBGtzxvD1Q/28sLi4NYZbfzkXEBnsf5gHbR7Fa5rI9jMkAVmTMNmFELKU4nfGJFFLM5coreuEbh97rTTa1XwqPVtXXqkL9GNhL93u85hnwBfWPyx7wWUHVdPF85ufnnsaS4+5OLdH/QDWsouNde0hF7Sma6faSXuTBULHD0pMg/1WlpXwg0KkwtlJfJR1vKJrA6n974krJlyc2RpyV3xgaEutkpvRnz+o7I/aNXTZv8esrSCaItM8Vz0poiGkU5B7/Rf2DbLLCbmGjJkJ4aLtXlMWHLkaydftnaaiK0hsM0qPiUAHYrxipBvyB+Jwyo764rRe8ppE81QzEt9giyarj8/S2sD1N4uNE8CLBqseEFmsyD2vPH2lPb5u+9zjOjRWSj3tAtgD3ViQBHHMALSV4aTjfWxHnMGilyDCY78e06xjZ23rQwv7dkW/uW1aIy0M+wfTyiYgzzowSbS4Vi7DwC/TNYjRf++MPPqHaB3x6R69osY1c4znl+Nc4dXiZ5R1ji8J1NNpzoRBPxDC9N0T0cOomhItfNkq7uW2NBEZAGjJIfhC5qXit4B5rd+s6almF3WyOeP5b5yAsAFHcHVb0RajiWXCpDwCcK52VjFsW0bgLm+k="
